all:
	echo "% This file is generated with the Makefile %" > .git.tex
	echo "% Please do not edit this file!            %\n" >> .git.tex
	echo "\\gdef\\git{" $(shell git rev-parse HEAD)@$(shell git rev-parse --abbrev-ref HEAD) "}" >> .git.tex
	pdflatex main.tex
